name: Deploy to Netlify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build hook
        run: curl -X POST -d '{}' "https://api.netlify.com/build_hooks/6a9b0d91d5ae301d817296d9"